# Generated by Django 4.1.7 on 2023-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_transactions_peopleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='startDate',
            field=models.DateField(),
        ),
    ]
